# Generated by Django 6.1 on 2026-09-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, help_text='Empty means this is the current price.', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'product price history',
                'ordering': ['-valid_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('product',), name='one_open_price_row_per_product'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='pricehist_valid_range')],
            },
        ),
    ]
