# Generated by Django 6.1 on 2026-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_history'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['category', 'status'], name='idx_product_cat_status_live'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=['metal_type', 'price'], name='idx_product_metal_price_live'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=['featured'], name='idx_product_featured_live'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='idx_product_created_desc'),
        ),
    ]
