# Generated by Django 6.1 on 2026-09-20 14:02

from django.db import migrations

CREATE_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION fn_track_product_price()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    -- clock_timestamp() is the real current time. now() would stay frozen
    -- for the whole transaction.
    v_now timestamptz := clock_timestamp();
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Django saves every column, so this can fire when only the name
        -- changed. Only a real price change should be recorded.
        IF NEW.price IS NOT DISTINCT FROM OLD.price THEN
            RETURN NULL;
        END IF;

        -- Close the price that was in force until now.
        UPDATE products_productpricehistory
           SET valid_to = GREATEST(v_now, valid_from)
         WHERE product_id = NEW.id
           AND valid_to IS NULL;
    END IF;

    -- Open the new price period (for INSERT this is the very first price).
    INSERT INTO products_productpricehistory
                (product_id, price, valid_from, valid_to)
    VALUES      (NEW.id, NEW.price, v_now, NULL);

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_price_history ON products_product;

CREATE TRIGGER trg_product_price_history
AFTER INSERT OR UPDATE OF price ON products_product
FOR EACH ROW
EXECUTE FUNCTION fn_track_product_price();
"""

# A trigger only sees FUTURE changes, so products that already exist get one
# "current price" row, starting from when they were created.
BACKFILL_SQL = """
INSERT INTO products_productpricehistory (product_id, price, valid_from, valid_to)
SELECT p.id, p.price, p.created_at, NULL
  FROM products_product p
 WHERE NOT EXISTS (
           SELECT 1
             FROM products_productpricehistory h
            WHERE h.product_id = p.id
       );
"""

DROP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS trg_product_price_history ON products_product;
DROP FUNCTION IF EXISTS fn_track_product_price();
"""


def install(apps, schema_editor):
    # Triggers are PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_TRIGGER_SQL, params=None)
    schema_editor.execute(BACKFILL_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_TRIGGER_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_trigram_indexes"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
