# Generated by Django 6.1 on 2026-09-20 14:08

from django.db import migrations

CREATE_SQL = """
CREATE OR REPLACE FUNCTION fn_sync_deleted_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_deleted AND NOT OLD.is_deleted AND NEW.deleted_at IS NULL THEN
        NEW.deleted_at := clock_timestamp();
    ELSIF NOT NEW.is_deleted AND OLD.is_deleted THEN
        NEW.deleted_at := NULL;
    END IF;

    -- BEFORE trigger: the returned row is the one that gets stored.
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_sync_deleted_at ON products_product;

CREATE TRIGGER trg_product_sync_deleted_at
BEFORE UPDATE OF is_deleted ON products_product
FOR EACH ROW
EXECUTE FUNCTION fn_sync_deleted_at();

DROP TRIGGER IF EXISTS trg_category_sync_deleted_at ON products_category;

CREATE TRIGGER trg_category_sync_deleted_at
BEFORE UPDATE OF is_deleted ON products_category
FOR EACH ROW
EXECUTE FUNCTION fn_sync_deleted_at();
"""

DROP_SQL = """
DROP TRIGGER IF EXISTS trg_category_sync_deleted_at ON products_category;
DROP TRIGGER IF EXISTS trg_product_sync_deleted_at ON products_product;
DROP FUNCTION IF EXISTS fn_sync_deleted_at();
"""


def install(apps, schema_editor):
    # Triggers are PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_price_history_trigger"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
