# Generated by Django 6.1 on 2026-09-20 14:10

from django.db import migrations

CREATE_SQL = """
-- The category itself plus all of its non-deleted descendants.
-- UNION (not UNION ALL) removes duplicates, so the query still ends
-- even if the data ever contained a cycle.
CREATE OR REPLACE FUNCTION fn_category_descendants(p_category_id bigint)
RETURNS SETOF bigint
LANGUAGE sql
STABLE
AS $$
    WITH RECURSIVE tree(id) AS (
        SELECT c.id
          FROM products_category c
         WHERE c.id = p_category_id

        UNION

        SELECT child.id
          FROM products_category child
          JOIN tree t ON child.parent_id = t.id
         WHERE child.is_deleted = FALSE
    )
    SELECT id FROM tree;
$$;


-- The price a product had at a given moment (NULL if it had none yet).
-- valid_to is exclusive: a period ends exactly when the next one begins.
CREATE OR REPLACE FUNCTION fn_get_price_at(p_product_id bigint, p_moment timestamptz)
RETURNS numeric
LANGUAGE sql
STABLE
AS $$
    SELECT h.price
      FROM products_productpricehistory h
     WHERE h.product_id = p_product_id
       AND h.valid_from <= p_moment
       AND (h.valid_to IS NULL OR h.valid_to > p_moment)
     ORDER BY h.valid_from DESC
     LIMIT 1;
$$;
"""

DROP_SQL = """
DROP FUNCTION IF EXISTS fn_get_price_at(bigint, timestamptz);
DROP FUNCTION IF EXISTS fn_category_descendants(bigint);
"""


def install(apps, schema_editor):
    # PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_soft_delete_triggers"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
