# Generated by Django 6.1 on 2026-09-20 14:11

from django.db import migrations

CREATE_SQL = """
-- Raise or lower the price of every non-deleted product in a category and
-- all of its sub-categories by a percentage.
--
--   CALL sp_adjust_category_prices(3, 10);     -- +10 %
--   CALL sp_adjust_category_prices(3, -15.5);  -- -15.5 %
--
-- Everything happens in one transaction: either every product is repriced
-- or none is.
CREATE OR REPLACE PROCEDURE sp_adjust_category_prices(
    p_category_id bigint,
    p_percent     numeric
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_factor  numeric;
    v_updated integer;
BEGIN
    IF p_percent IS NULL OR p_percent < -90 OR p_percent > 500 THEN
        RAISE EXCEPTION 'Percent change must be between -90 and 500 (got %).', p_percent
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM products_category
         WHERE id = p_category_id
           AND is_deleted = FALSE
    ) THEN
        RAISE EXCEPTION 'Category % does not exist or is deleted.', p_category_id
            USING ERRCODE = 'no_data_found';
    END IF;

    v_factor := 1 + (p_percent / 100.0);

    UPDATE products_product
       SET price      = ROUND(price * v_factor, 2),
           updated_at = clock_timestamp()
     WHERE is_deleted = FALSE
       AND category_id IN (SELECT * FROM fn_category_descendants(p_category_id));

    GET DIAGNOSTICS v_updated = ROW_COUNT;

    RAISE NOTICE 'Adjusted the price of % product(s) by % percent.', v_updated, p_percent;
END;
$$;
"""

DROP_SQL = """
DROP PROCEDURE IF EXISTS sp_adjust_category_prices(bigint, numeric);
"""


def install(apps, schema_editor):
    # PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_helper_functions"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
