# Generated by Django 6.1 on 2026-09-20 14:14

from django.db import migrations

CREATE_SQL = """
-- Products a customer can buy, with category, cover image and rating.
DROP VIEW IF EXISTS vw_active_product_catalog;

CREATE VIEW vw_active_product_catalog AS
SELECT p.id                                 AS product_id,
       p.name,
       p.slug,
       p.sku,
       c.id                                 AS category_id,
       c.name                               AS category_name,
       p.metal_type,
       p.purity,
       p.weight_grams,
       p.price,
       p.stock,
       p.featured,
       COALESCE(rs.average_rating, 0)       AS average_rating,
       COALESCE(rs.review_count, 0)         AS review_count,
       (SELECT img.image
          FROM products_productimage img
         WHERE img.product_id = p.id
           AND img.is_primary
         ORDER BY img.id
         LIMIT 1)                           AS cover_image,
       p.created_at
  FROM products_product p
  JOIN products_category c
    ON c.id = p.category_id
  LEFT JOIN reviews_productratingsummary rs
    ON rs.product_id = p.id
 WHERE p.is_deleted = FALSE
   AND p.status = 'active';


-- One row per non-deleted category, counting the products placed directly
-- in that category. inventory_value = sum(price * stock).
DROP VIEW IF EXISTS vw_category_inventory_summary;

CREATE VIEW vw_category_inventory_summary AS
SELECT c.id                                           AS category_id,
       c.name                                         AS category_name,
       parent.name                                    AS parent_name,
       COUNT(p.id)                                    AS total_products,
       COUNT(p.id) FILTER (WHERE p.status = 'active') AS active_products,
       COALESCE(SUM(p.stock), 0)                      AS total_stock,
       MIN(p.price)                                   AS min_price,
       MAX(p.price)                                   AS max_price,
       ROUND(AVG(p.price), 2)                         AS avg_price,
       COALESCE(SUM(p.price * p.stock), 0)            AS inventory_value
  FROM products_category c
  LEFT JOIN products_category parent
         ON parent.id = c.parent_id
  LEFT JOIN products_product p
         ON p.category_id = c.id
        AND p.is_deleted = FALSE
 WHERE c.is_deleted = FALSE
 GROUP BY c.id, c.name, parent.name;
"""

DROP_SQL = """
DROP VIEW IF EXISTS vw_category_inventory_summary;
DROP VIEW IF EXISTS vw_active_product_catalog;
"""


def install(apps, schema_editor):
    # Views use PostgreSQL features. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_adjust_prices_procedure"),
        # The catalog view joins the rating summary table.
        ("reviews", "0005_recalculate_ratings_procedure"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
