# Generated by Django 6.1 on 2026-09-20 14:16

from django.db import migrations

CREATE_SQL = """
-- Every price period of every product, plus the change compared with the
-- previous period. LAG() is a window function: it reads the previous row of
-- the same product, ordered by valid_from.
DROP VIEW IF EXISTS vw_product_price_timeline;

CREATE VIEW vw_product_price_timeline AS
SELECT h.id                                  AS history_id,
       p.id                                  AS product_id,
       p.name                                AS product_name,
       p.sku,
       h.price,
       h.valid_from,
       h.valid_to,
       (h.valid_to IS NULL)                  AS is_current,
       h.price - LAG(h.price) OVER w         AS change_from_previous,
       ROUND(
           100.0 * (h.price - LAG(h.price) OVER w)
                 / NULLIF(LAG(h.price) OVER w, 0),
           2
       )                                     AS change_percent
  FROM products_productpricehistory h
  JOIN products_product p
    ON p.id = h.product_id
WINDOW w AS (PARTITION BY h.product_id ORDER BY h.valid_from);


-- One row per active, non-staff customer, with counts from three other
-- tables. Separate sub-selects keep each count independent, so the counts
-- cannot multiply each other.
DROP VIEW IF EXISTS vw_customer_activity;

CREATE VIEW vw_customer_activity AS
SELECT u.id          AS user_id,
       u.username,
       u.city,
       u.date_joined,
       (SELECT COUNT(*)
          FROM wishlists_wishlist w
         WHERE w.user_id = u.id)                          AS wishlist_items,
       (SELECT COALESCE(SUM(ci.quantity), 0)
          FROM cart_cart ct
          JOIN cart_cartitem ci ON ci.cart_id = ct.id
         WHERE ct.user_id = u.id)                         AS cart_units,
       (SELECT COUNT(*)
          FROM reviews_review r
         WHERE r.user_id = u.id
           AND r.is_deleted = FALSE)                      AS reviews_written,
       (SELECT ROUND(AVG(r.rating), 2)
          FROM reviews_review r
         WHERE r.user_id = u.id
           AND r.is_deleted = FALSE)                      AS avg_rating_given
  FROM accounts_user u
 WHERE u.is_active = TRUE
   AND u.is_staff = FALSE;
"""

DROP_SQL = """
DROP VIEW IF EXISTS vw_customer_activity;
DROP VIEW IF EXISTS vw_product_price_timeline;
"""


def install(apps, schema_editor):
    # Views use PostgreSQL features. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_catalog_views"),
        # The customer view reads these tables.
        ("accounts", "0008_emailotp_index"),
        ("cart", "0001_initial"),
        ("wishlists", "0001_initial"),
        ("reviews", "0005_recalculate_ratings_procedure"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
