# Generated by Django 6.1 on 2026-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
