# Generated by Django 6.1 on 2026-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='idx_otp_user_purpose_created'),
        ),
    ]
