# Generated by Django 6.1 on 2026-09-20 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_indexes'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['product', '-created_at'], name='idx_review_product_live'),
        ),
    ]
