# Generated by Django 6.1 on 2026-09-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_price_history_trigger'),
        ('reviews', '0002_review_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRatingSummary',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating_summary', serialize=False, to='products.product')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'product rating summaries',
            },
        ),
    ]
