# Generated by Django 6.1 on 2026-09-20 14:06

from django.db import migrations

CREATE_SQL = """
-- Recompute the average and count of ONE product and store them.
CREATE OR REPLACE FUNCTION fn_refresh_product_rating(p_product_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_count integer;
    v_avg   numeric(3, 2);
BEGIN
    -- If two reviews of the same product are saved at the same moment,
    -- make the second one wait, so it recomputes after the first has
    -- committed. The lock is released automatically at COMMIT/ROLLBACK.
    PERFORM pg_advisory_xact_lock(p_product_id);

    SELECT COUNT(*),
           COALESCE(ROUND(AVG(r.rating), 2), 0)
      INTO v_count, v_avg
      FROM reviews_review r
     WHERE r.product_id = p_product_id
       AND r.is_deleted = FALSE;

    -- UPDATE only, never INSERT (see the explanation above).
    UPDATE reviews_productratingsummary
       SET average_rating = v_avg,
           review_count   = v_count,
           updated_at     = clock_timestamp()
     WHERE product_id = p_product_id;
END;
$$;


-- Trigger function for reviews_review.
CREATE OR REPLACE FUNCTION fn_review_rating_summary()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM fn_refresh_product_rating(OLD.product_id);
    ELSE
        PERFORM fn_refresh_product_rating(NEW.product_id);

        -- A review moved to another product: refresh the old one too.
        -- (Nested IFs on purpose: OLD does not exist during an INSERT.)
        IF TG_OP = 'UPDATE' THEN
            IF OLD.product_id IS DISTINCT FROM NEW.product_id THEN
                PERFORM fn_refresh_product_rating(OLD.product_id);
            END IF;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_review_rating_summary ON reviews_review;

CREATE TRIGGER trg_review_rating_summary
AFTER INSERT OR UPDATE OF rating, is_deleted, product_id OR DELETE
ON reviews_review
FOR EACH ROW
EXECUTE FUNCTION fn_review_rating_summary();


-- Trigger function for products_product: every new product starts with an
-- empty summary row.
CREATE OR REPLACE FUNCTION fn_init_product_rating_summary()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO reviews_productratingsummary
                (product_id, average_rating, review_count, updated_at)
    VALUES      (NEW.id, 0, 0, clock_timestamp())
    ON CONFLICT (product_id) DO NOTHING;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_init_rating_summary ON products_product;

CREATE TRIGGER trg_product_init_rating_summary
AFTER INSERT ON products_product
FOR EACH ROW
EXECUTE FUNCTION fn_init_product_rating_summary();
"""

# Triggers only see FUTURE changes, so fill in the products that exist already.
BACKFILL_SQL = """
INSERT INTO reviews_productratingsummary
            (product_id, average_rating, review_count, updated_at)
SELECT p.id,
       COALESCE(ROUND(AVG(r.rating), 2), 0),
       COUNT(r.id),
       clock_timestamp()
  FROM products_product p
  LEFT JOIN reviews_review r
         ON r.product_id = p.id
        AND r.is_deleted = FALSE
 GROUP BY p.id
ON CONFLICT (product_id) DO UPDATE
   SET average_rating = EXCLUDED.average_rating,
       review_count   = EXCLUDED.review_count,
       updated_at     = EXCLUDED.updated_at;
"""

DROP_SQL = """
DROP TRIGGER IF EXISTS trg_product_init_rating_summary ON products_product;
DROP TRIGGER IF EXISTS trg_review_rating_summary ON reviews_review;
DROP FUNCTION IF EXISTS fn_init_product_rating_summary();
DROP FUNCTION IF EXISTS fn_review_rating_summary();
DROP FUNCTION IF EXISTS fn_refresh_product_rating(bigint);
"""


def install(apps, schema_editor):
    # Triggers are PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)
    schema_editor.execute(BACKFILL_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rating_summary"),
        ("products", "0010_price_history_trigger"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
