# Generated by Django 6.1 on 2026-09-20 14:12

from django.db import migrations

CREATE_SQL = """
-- Rebuild the rating summary of EVERY product from the reviews table.
--
--   CALL sp_recalculate_all_ratings();
--
-- One set-based statement (no row-by-row loop). Products without reviews
-- get average 0 and count 0.
CREATE OR REPLACE PROCEDURE sp_recalculate_all_ratings()
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO reviews_productratingsummary
                (product_id, average_rating, review_count, updated_at)
    SELECT p.id,
           COALESCE(ROUND(AVG(r.rating), 2), 0),
           COUNT(r.id),
           clock_timestamp()
      FROM products_product p
      LEFT JOIN reviews_review r
             ON r.product_id = p.id
            AND r.is_deleted = FALSE
     GROUP BY p.id
    ON CONFLICT (product_id) DO UPDATE
       SET average_rating = EXCLUDED.average_rating,
           review_count   = EXCLUDED.review_count,
           updated_at     = EXCLUDED.updated_at;
END;
$$;
"""

DROP_SQL = """
DROP PROCEDURE IF EXISTS sp_recalculate_all_ratings();
"""


def install(apps, schema_editor):
    # PostgreSQL-only. Skip elsewhere (e.g. SQLite in CI).
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(CREATE_SQL, params=None)


def uninstall(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(DROP_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_rating_summary_triggers"),
    ]

    operations = [
        migrations.RunPython(install, uninstall),
    ]
